name: KillAdminForMoney
version: 993
main: zxc.deadinside.sayboom.killadminformoney.KillAdminForMoney
api-version: 1.16
depend:
  - LuckPerms

commands:
  kafm:
    usage: /<command> reload
    permission: kafm.reload
    permission-message: '&cУ тебя нет прав на эту команду.'

